---
name: Continuous Integration - Super-Linter

on:
  pull_request:
    branches:
      - main
  push: {} #faz em todos os repositórios

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    env:
      VALIDATE_JAVA_GOOGLE_FORMAT: false  # Google Java Format desativado
      VALIDATE_JAVA: true  # Mantém outros linters de Java
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Histórico completo para o Super-Linter

      - name: Super-linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
