name: Super-Linter

on:
  pull_request:
    branches:
      - main
  push: {} # Dispara em todos os branches

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    env:
      VALIDATE_JAVA_GOOGLE_FORMAT: false
      VALIDATE_JAVA: true
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  notify-whatsapp: # Job separado
    name: Notificação WhatsApp
    runs-on: ubuntu-latest
    needs: build # Garante execução após o job 'build'
    permissions:
      contents: read # Permissão mínima necessária
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send WhatsApp Notification
        uses: KnosTx/whatsapp-notification-action@v1
        with:
          whatsapp_invite_link: ${{secrets.WHATSAPP_URL}}