---
name: Continuous Delivery

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions: {}

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projeto.zip
          path: |
            src/
            README.md

