name: Continuous Integration - Super-Linter and Discord

on:
  pull_request:
    branches:
      - main
  push: {} # Dispara em todos os branches

permissions: {}

jobs:
  build:  # Primeiro job
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    env:
      VALIDATE_JAVA: true
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  discord:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook_url: ${{ secrets.discord_webhook }}
          template: "avatar-with-link"
          include-extras: true