name: Continuous-Integration

on:
  push: {} # Dispara em todos os branches

permissions: {}

jobs:
  build:
    name: Java-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VALIDATE_ALL_CODEBASE: true  # Analisa tudo
      # Exceções:
      VALIDATE_MARKDOWN: false      # Ignora Markdown
      VALIDATE_YAML_PRETTIER: false # Ignora Prettier para YAML

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
